ARG VERSION=11.5.2

FROM grafana/grafana-oss:${VERSION}

# Copy datasources provisioning
COPY datasources /etc/grafana/provisioning/datasources

# Copy dashboards provisioning (Joyce dashboards)
COPY dashboards /etc/grafana/provisioning/dashboards

# Copy alerting rules provisioning
COPY alerting /etc/grafana/provisioning/alerting
